# https://typst.app/blog/2023/package-manager/
# https://github.com/typst/packages
[package]
name = "minimal-styling"
version = "0.1.0"
compiler = "0.11.0"
entrypoint = "src/lib.typ"

authors = ["ziv3@outlook.com"]

repository = "https://github.com/icyzeroice/typst-template-minimal-note"
license = "MIT"

keywords = ["minimal", "github markdown"]
description = "Minimal styling for typst to look like github markdown preview."
categories = ["layout", "presentation"]

[template]
path = "sample"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"
